"""empty message

Revision ID: f9f97fd76920
Revises: 4d7ab762453a
Create Date: 2022-01-12 11:20:28.589632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f97fd76920'
down_revision = '4d7ab762453a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_user_organization', sa.Column('team_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_user_organization', 'team_id')
    # ### end Alembic commands ###
