"""Added public_registration to org

Revision ID: a5975fec3593
Revises: f9f97fd76920
Create Date: 2022-01-17 13:39:31.277802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5975fec3593'
down_revision = 'f9f97fd76920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('public_registration', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'public_registration')
    # ### end Alembic commands ###
