version: "3.4"
x-restart-policy:
  restart: always
services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  postgres:
    env_file:
      - dev.env
    image: "postgres:9-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "dispatch-postgres-1:/var/lib/postgresql/data"
  redis:
    env_file:
      - dev.env
    image: "redis"
    ports:
      - "6379:6379"
volumes:
  dispatch-postgres-1:
    # external:
    #   name: dispatch-postgres-1
