"""empty message

Revision ID: 0fcf9d387a0f
Revises: bfa07b9a1c31
Create Date: 2022-01-18 15:18:53.489766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0fcf9d387a0f'
down_revision = 'bfa07b9a1c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('item_inventory_search_vector_idx', table_name='item_inventory')
    op.drop_column('item_inventory', 'search_vector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_inventory', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('item_inventory_search_vector_idx', 'item_inventory', ['search_vector'], unique=False)
    # ### end Alembic commands ###
