"""empty message

Revision ID: bfa07b9a1c31
Revises: 
Create Date: 2022-01-17 18:59:45.968662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa07b9a1c31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dispatch_user_managed_teams', 'dispatch_user', [
                          'user_id'], ['id'], referent_schema='dispatch_core')
    op.create_foreign_key(None, 'service_plugin', 'plugin', ['plugin_id'], [
                          'id'], referent_schema='dispatch_core')
    op.create_foreign_key(None, 'worker', 'dispatch_user', ['dispatch_user_id'], [
                          'id'], referent_schema='dispatch_core')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_constraint(None, 'service_plugin', type_='foreignkey')
    op.drop_constraint(None, 'dispatch_user_managed_teams', type_='foreignkey')
    # ### end Alembic commands ###
