"""empty message

Revision ID: 0aba0a0587ff
Revises: 5fa2662e298d
Create Date: 2021-10-21 09:03:24.936580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aba0a0587ff'
down_revision = '5fa2662e298d'
branch_labels = "added loaded_items to worker"
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('loaded_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'loaded_items')
    # ### end Alembic commands ###
