"""empty message

Revision ID: 20e7290c6745
Revises: 795e34c35862
Create Date: 2021-11-17 11:10:25.733206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e7290c6745'
down_revision = '795e34c35862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('requested_items', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('job', sa.Column('requested_skills', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'requested_skills')
    op.drop_column('job', 'requested_items')
    # ### end Alembic commands ###
