"""Added dispatch_user.is_active

Revision ID: 218c1377502e
Revises: 750be18e5541
Create Date: 2022-01-05 16:54:40.840559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218c1377502e'
down_revision = '750be18e5541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_user', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_user', 'is_active')
    # ### end Alembic commands ###
