"""Added loaded_items for workers

Revision ID: 390951c2a6ef
Revises: 4d254638982d
Create Date: 2021-11-17 14:39:35.105836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390951c2a6ef'
down_revision = '4d254638982d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('loaded_items', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'loaded_items')
    # ### end Alembic commands ###
