"""empty message

Revision ID: 4d254638982d
Revises: 88c37aba4e4d
Create Date: 2021-11-17 14:36:49.078561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d254638982d'
down_revision = '88c37aba4e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('worker', 'loaded_items')
    op.drop_column('worker', 'requested_skills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('requested_skills', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('worker', sa.Column('loaded_items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('worker', 'skills')
    # ### end Alembic commands ###
