"""Added managed teams to auth.dispatch_user, added team_id to location

Revision ID: 4f5461b1433c
Revises: b17129c985b4
Create Date: 2022-01-03 12:38:31.975729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5461b1433c'
down_revision = 'b17129c985b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_user_managed_teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dispatch_user.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    op.add_column('dispatch_user_organization', sa.Column('team_id', sa.Integer(), nullable=False))
    op.add_column('location', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'location', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'team_id')
    op.drop_column('dispatch_user_organization', 'team_id')
    op.drop_table('dispatch_user_managed_teams')
    # ### end Alembic commands ###
