"""empty message

Revision ID: 6fbebd4901a8
Revises: a1fd20e0d493
Create Date: 2021-09-14 15:15:34.401440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbebd4901a8'
down_revision = 'a1fd20e0d493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_org_code', 'job', ['code', 'org_id'])
    op.drop_constraint('job_code_key', 'job', type_='unique')
    op.alter_column('location', 'location_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uix_org_location_code', 'location', ['location_code', 'org_id'])
    op.drop_constraint('location_location_code_key', 'location', type_='unique')
    op.alter_column('service', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('_code_org_id_unique', 'service', ['org_id', 'code'])
    op.drop_constraint('service_code_key', 'service', type_='unique')
    op.create_unique_constraint('uix_org_id_worker_code', 'worker', ['code', 'org_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_org_id_worker_code', 'worker', type_='unique')
    op.create_unique_constraint('service_code_key', 'service', ['code'])
    op.drop_constraint('_code_org_id_unique', 'service', type_='unique')
    op.alter_column('service', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('location_location_code_key', 'location', ['location_code'])
    op.drop_constraint('uix_org_location_code', 'location', type_='unique')
    op.alter_column('location', 'location_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('job_code_key', 'job', ['code'])
    op.drop_constraint('uix_org_code', 'job', type_='unique')
    # ### end Alembic commands ###
