"""replaced worker.auth_username (str) by worker.dispatch_user FK.

Revision ID: 750be18e5541
Revises: 4f5461b1433c
Create Date: 2022-01-03 22:11:00.967092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750be18e5541'
down_revision = '4f5461b1433c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('dispatch_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'worker', 'dispatch_user', ['dispatch_user_id'], ['id'])
    op.drop_column('worker', 'auth_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('auth_username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'worker', type_='foreignkey')
    op.drop_column('worker', 'dispatch_user_id')
    # ### end Alembic commands ###
