"""Fixed item inventory event -> code data type.

Revision ID: 795e34c35862
Revises: ee786cbdc589
Create Date: 2021-10-24 21:35:20.910487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795e34c35862'
down_revision = 'ee786cbdc589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
