"""empty message

Revision ID: 88c37aba4e4d
Revises: 20e7290c6745
Create Date: 2021-11-17 13:49:31.817151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c37aba4e4d'
down_revision = '20e7290c6745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker', sa.Column('requested_skills', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker', 'requested_skills')
    # ### end Alembic commands ###
