"""empty message

Revision ID: c0f14fe65c1a
Revises: 5a94467eb8a7
Create Date: 2021-06-17 12:33:56.701753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f14fe65c1a'
down_revision = '5a94467eb8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_type', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'job_type')
    # ### end Alembic commands ###
