"""added allocated_qty

Revision ID: ee219d129667
Revises: fc74b1aba66d
Create Date: 2021-10-23 14:40:37.940331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee219d129667'
down_revision = 'fc74b1aba66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_inventory', sa.Column('allocated_qty', sa.Float(), nullable=False))
    op.add_column('item_inventory', sa.Column('curr_qty', sa.Float(), nullable=False))
    op.drop_column('item_inventory', 'qty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_inventory', sa.Column('qty', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('item_inventory', 'curr_qty')
    op.drop_column('item_inventory', 'allocated_qty')
    # ### end Alembic commands ###
