"""added inventory event

Revision ID: ee786cbdc589
Revises: ee219d129667
Create Date: 2021-10-24 21:14:15.552733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
# revision identifiers, used by Alembic.
revision = 'ee786cbdc589'
down_revision = 'ee219d129667'
branch_labels = "added inventory event"
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_inventory_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('details', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('depot_code', sa.String(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_code', sa.String(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('account_code', sa.String(), nullable=True),
    sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index('ix_item_inventory_event_search_vector', 'item_inventory_event', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_item_inventory_event_search_vector', table_name='item_inventory_event')
    op.drop_table('item_inventory_event')
    # ### end Alembic commands ###
