"""added column 'job.life_cycle_status'

Revision ID: f9bfe7d9ee98
Revises: 218c1377502e
Create Date: 2022-01-06 19:21:36.432783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bfe7d9ee98'
down_revision = '218c1377502e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('life_cycle_status', sa.String(), nullable=True))
    op.execute("UPDATE job SET life_cycle_status = 'Created'")
    op.alter_column('job', 'life_cycle_status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'life_cycle_status')
    # ### end Alembic commands ###
