"""max_volume etc for depot

Revision ID: fc74b1aba66d
Revises: 0aba0a0587ff
Create Date: 2021-10-22 14:33:57.426291

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc74b1aba66d'
down_revision = '0aba0a0587ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depot', sa.Column('max_volume', sa.Integer(), nullable=True))
    op.add_column('depot', sa.Column('max_weight', sa.Integer(), nullable=True))
    op.drop_index('ix_item_inventory_search_vector', table_name='item_inventory')
    op.drop_column('item_inventory', 'search_vector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_inventory', sa.Column('search_vector',
                  postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_item_inventory_search_vector',
                    'item_inventory', ['search_vector'], unique=False)
    op.drop_column('depot', 'max_weight')
    op.drop_column('depot', 'max_volume')
    # ### end Alembic commands ###
